server.port: "8089"
spring:
  data:
    rest:
      base-path: /api
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/MenuRest
    username: sa
    password: ""
  h2:
    console:
      enabled: "true"
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: "true"
#endpoints:
#  mappings:
#    sensitive: "false"
#  env:
#    sensitive: "false"

  http:
    multipart:
      enabled: true
      multipart.max-file-size: 10MB
      multipart.max-request-size: 10MB

  freemarker:
    template-loader-path: /
    freemarker.suffix: .ftl

logging:
  level:
    org:
      springframework: ERROR

#Default login and password
app:
  login: "admin"
  password: "password"